apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  limits:
    resources:
      cpu: 1000
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.medium", "t3.large", "t3a.medium"]
    - key: "node.kubernetes.io/instance-type"
      operator: NotIn
      values: ["p5en.48xlarge"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-northeast-2a", "ap-northeast-2c"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
  provider:
    subnetSelector:
      kubernetes.io/role/karpenter: "1"
    securityGroupSelector:
      karpenter.sh/discovery: "njt-eks-petclinic"
    instanceProfile: "KarpenterNodeInstanceProfile"
    amiFamily: "AL2"
  ttlSecondsAfterEmpty: 30

