name: Build & Deploy Web

on:
  push:
    branches:
      - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-2

    steps:
      - name: Checkout web repo
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=web-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker image
        run: |
          docker build -t 620832535900.dkr.ecr.ap-northeast-2.amazonaws.com/web:${IMAGE_TAG} .
          docker push 620832535900.dkr.ecr.ap-northeast-2.amazonaws.com/web:${IMAGE_TAG}

      - name: Clone manifests repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/Zaaaaaay/manifests.git
          cd manifests
          git config user.name "ci-bot"
          git config user.email "ci@example.com"

      - name: Update deployment YAML
        run: |
          set -e
          echo "Before sed:"
          grep image manifests/web-deployment.yaml

          sed -i -E "s|^[[:space:]]*image:.*|          image: i620832535900.dkr.ecr.ap-northeast-2.amazonaws.com/web:${IMAGE_TAG}|" manifests/web-deployment.yaml

          echo "After sed:"
          grep image manifests/web-deployment.yaml

          git -C manifests add web-deployment.yaml
          git -C manifests commit -m "Update image tag to ${IMAGE_TAG}" || echo "Nothing to commit"
          git -C manifests push origin main

