name: Build & Deploy Web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout web repo
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=web-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        run: |
          aws configure set region ap-northeast-2
          aws ecr get-login-password | docker login --username AWS --password-stdin 620832535900.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build & Push Docker image
        run: |
          docker build -t 620832535900.dkr.ecr.ap-northeast-2.amazonaws.com/web:${IMAGE_TAG} .
          docker push 620832535900.dkr.ecr.ap-northeast-2.amazonaws.com/web:${IMAGE_TAG}

      - name: Clone manifests repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/Zaaaaaay/manifests.git
          cd manifests
          git config user.name "ci-bot"
          git config user.email "ci@example.com"

      - name: Update deployment YAML
        run: |
          set -e
          cd manifests
          echo "Before sed:"
          grep image web-deployment.yaml

          sed -i -E "s|(image:\s*).*|\1i620832535900.dkr.ecr.ap-northeast-2.amazonaws.com/web:${IMAGE_TAG}|" web-deployment.yaml

          echo "After sed:"
          grep image web-deployment.yaml

          git add web-deployment.yaml
          git diff --cached
          git commit -m "Update image tag to ${IMAGE_TAG}" || echo "Nothing to commit"
          git push origin main

